services:
  manager:
    image: shimady563/coding-contest-manager
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contest
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_TOKEN_ACCESS_SECRET=e2572ccf3dad3fbae0d34ab2d395a3d8d538d9031b0c3037f302c077c344cd6c75e15ab7a5322fcf35e87d1ad3e813008f7bff153d4b912d358da6707ff10825
      - JWT_TOKEN_ACCESS_EXPIRATION=21600000
      - JWT_TOKEN_ACCESS_COOKIE_NAME=coding_contest_system_access_token
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:8080/api/v1/actuator/health' ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy

  compiler:
    image: shimady563/coding-contest-compiler
    ports:
      - '8082:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contest
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      manager:
        condition: service_healthy
      auth:
        condition: service_started
      postgres:
        condition: service_healthy

  auth:
    image: shimady563/coding-contest-auth
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/contest
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=redis
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_TOKEN_ACCESS_SECRET=e2572ccf3dad3fbae0d34ab2d395a3d8d538d9031b0c3037f302c077c344cd6c75e15ab7a5322fcf35e87d1ad3e813008f7bff153d4b912d358da6707ff10825
      - JWT_TOKEN_ACCESS_EXPIRATION=21600000
      - JWT_TOKEN_ACCESS_COOKIE_NAME=coding_contest_system_access_token
      - JWT_TOKEN_REFRESH_SECRET=4e7dd4cfb4136b7aefd2560492b843a9c5cd006553dbb4c3f6e3ddbdac5fe1e67534ede1045df8ca0e88790e9df24a2e567bc0a3196663890825a012e3717adc
      - JWT_TOKEN_REFRESH_EXPIRATION=604800000
      - JWT_TOKEN_REFRESH_COOKIE_NAME=coding_contest_system_refresh_token
    depends_on:
      manager:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  frontend:
    image: shimady563/coding-contest-frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_APP_MANAGER_URL=http://localhost:8080/api/v1
      - VITE_APP_AUTH_URL=http://localhost:8081/api/v1/auth
    depends_on:
      manager:
        condition: service_healthy
      auth:
        condition: service_started
      compiler:
        condition: service_started

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    user: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=contest
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:alpine
    command:
      [
        'redis-server',
        '--save',
        '',
        '--appendonly',
        'no',
        '--requirepass',
        'redis',
      ]
    restart: always
    volumes:
      - redis-data:/data
    expose:
      - 6379
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    restart: always
    expose:
      - 22181
    environment:
      - ZOOKEEPER_CLIENT_PORT=22181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    restart: always
    expose:
      - 9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:22181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - zookeeper

volumes:
  postgres-data:
  redis-data:
