# project properties
version=1.1.2
group=com.shimady.coding.contest.system

# gradle properties
org.gradle.daemon=false

# versions
springbootVersion=3.5.0
springDependencyManagementVersion=1.1.7
mapstructVersion=1.6.3
jsonWebTokenVersion=0.12.6
springdocOpenapiStarterWebmvcUiVersion=2.8.13
sonarQubeVersion=7.0.1.6134

# SonarQube properties
systemProp.sonar.projectKey=coding-contest-system
systemProp.sonar.organization=shimady
systemProp.sonar.projectName=Coding Contest System
systemProp.sonar.projectVersion=${version}
systemProp.sonar.host.url=http://localhost:9000
systemProp.sonar.token=