auth:
  replicas: 1
  dockerImageName: coding-contest-compiler
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi

  profiles: prod

  server:
    basePath: /api/v1/compiler
    port: 8082

  timeoutSeconds: 10
  masOutputBytes: 1000000
  workdir: /cpp

  logLevel:
    root: INFO
    compiler: INFO
