spring:
  application:
    name: Compiler
  datasource:
    driver-class-name: org.postgresql.Driver
  kafka:
    listener:
      ack-mode: record
      concurrency: 1
    consumer:
      client-id: ${spring.application.name}
      group-id: ${spring.application.name}-submission
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.shimady563.contest.manager.model
            type:
              mapping: com.shimady563.contest.manager.model.dto.CodeSubmission:com.shimady.contest.compiler.model.dto.CodeSubmission

kafka:
  topics:
    submission:
      name: submissionTopic
      replication-factor: 1
      partitions: 4

compiler:
  timeout-seconds: 15
  max-output-bytes: 1_000_000
  workdir: /cpp

logging:
  level:
    root: info