apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
data:
  VITE_APP_MANAGER_URL: {{ .Values.frontend.managerUrl | quote }}
  VITE_APP_AUTH_URL: {{ .Values.frontend.authUrl | quote }}
