apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          serviceAccountName: {{ .Values.global.serviceAccount }}
          image: {{ .Values.global.docker.repositoryName }}/{{ .Values.frontend.dockerImageName }}:{{ .Values.global.docker.tag }}
          ports:
            - name: Frontend
              protocol: TCP
              containerPort: {{ .Values.frontend.internalPort }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.frontend.internalPort }}
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.frontend.internalPort }}
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          env:
            envFrom:
              configMap:
                name: {{ .Chart.Name }}-config