apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include  }}
spec:
  selector:
    {{ include }}
  ports:
    - name: Frontend
      protocol: TCP
      port: {{ .Values.frontend.externalPort }}
      targetPort: {{ .Values.frontend.internalPort }}