apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
type: Opaque
stringData:
  KAFKA_KRAFT_MODE: "{{ .Values.kafka.kraft.enabled }}"
  KAFKA_PROCESS_ROLES: "controller,broker"
  KAFKA_NODE_ID: "{{ .Values.kafka.nodeId }}"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "{{ .Values.kafka.kraft.controllerQuorumVoters }}"

  KAFKA_LISTENERS: "{{ .Values.kafka.listeners.listeners }}"
  KAFKA_ADVERTISED_LISTENERS: "{{ .Values.kafka.listeners.advertisedListeners }}"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "{{ .Values.kafka.listeners.securityProtocolMap }}"
  KAFKA_INTER_BROKER_LISTENER_NAME: "{{ .Values.kafka.listeners.interBrokerListenerName }}"
  KAFKA_CONTROLLER_LISTENER_NAMES: "{{ .Values.kafka.listeners.controllerListenerNames }}"

  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "{{ .Values.kafka.autoCreateTopics }}"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "{{ .Values.kafka.offsetsReplicationFactor }}"

  CLUSTER_ID: "{{ .Values.kafka.kraft.clusterId }}"
