apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
  ports:
    - name: broker
      port: {{ .Values.service.brokerPort }}
      targetPort: {{ .Values.service.brokerPort }}
    - name: controller
      port: {{ .Values.service.controllerPort }}
      targetPort: {{ .Values.service.controllerPort }}

