apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: "{{ .Values.global.db.name }}"
  POSTGRES_USER: "{{ .Values.global.db.username }}"
  POSTGRES_PASSWORD: "{{ .Values.global.db.password }}"
  POSTGRES_HOST: "{{ .Values.global.db.host }}"
  POSTGRES_PORT: "{{ .Values.global.db.port }}"
