apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "manager.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.manager.profiles | quote | default "prod" }}

  AUTH_WHITELIST: {{ .Values.manager.whitelist | quote }}
  AUTH_ALLOWED_ORIGINS: {{ .Values.manager.allowedOrigins | quote }}

  SERVER_SERVLET_CONTEXT_PATH: {{ .Values.manager.server.basePath | quote }}
  SERVER_PORT: {{ .Values.manager.server.internalPort | quote }}

  LOGGING_LEVEL_ROOT: {{ .Values.manager.logLevel.root | quote | default "INFO" }}
  LOGGING_LEVEL_COM_SHIMADY563_CONTEST_MANAGER: {{ .Values.manager.logLevel.manager | quote | default "INFO" }}

  KAFKA_PRODUCER_LINGER_MS: {{ .Values.manager.kafka.linger | quote }}
  KAFKA_PRODUCER_RETRY_BACKOFF_MS: {{ .Values.manager.kafka.retryBackoff | quote }}
  KAFKA_PRODUCER_DELIVERY_TIMEOUT_MS: {{ .Values.manager.kafka.deliveryTimeout | quote }}

  KAFKA_TOPICS_SUBMISSION_NAME: {{ .Values.global.kafka.topics.submission.name | quote }}
  KAFKA_TOPICS_SUBMISSION_REPLICATION_FACTOR: {{ .Values.global.kafka.topics.submission.replicationFactor | quote }}
  KAFKA_TOPICS_SUBMISSION_PARTITIONS: {{ .Values.global.kafka.topics.submission.partitions | quote }}

  HOUSEKEEPING_SOLUTION_KEEP_DAYS: {{ .Values.manager.housekeeping.solutionKeepDays | quote }}
