apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{ include  }}
data:
  spring.profiles.active: {{ .Values.manager.profiles | default "prod" }}

  auth.whitelist: {{ .Values.manager.whitelist | quote }}
  auth.allowed-origins: {{ .Values.manager.allowedOrigins | quote }}

  server.servlet.context-path: {{ .Values.manager.server.basePath }}
  server.servlet.port: {{ .Values.manager.server.internalPort }}

  logging.level.root: {{ .Values.manager.logLevel.root | default "INFO" }}
  logging.level.com.shimady563.contest.manager: {{ .Values.manager.logLevel.manager | default "INFO" }}

  kafka.producer.linger-ms: {{ .Values.manager.kafka.linger }}
  kafka.producer.retry-backoff-ms: {{ .Values.manager.kafka.retryBackoff }}
  kafka.producer.delivery-timeout-ms: {{ .Values.manager.kafka.deliveryTimeout }}

  kafka.topics.submission:
      {{- toYaml .Values.global.kafka.topics.submission | nindent 4 }}

  housekeeping.solution-keep-days: {{ .Values.manager.housekeeping.solutionKeepDays | default 180 }}

