apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.manager.replicas }}
  selector:
    matchLabels:
      {{- include "manager.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "manager.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          serviceAccountName: {{ .Values.global.serviceAccount }}
          image: {{ .Values.global.dockerRepositoryName }}/{{ .Values.manager.dockerImageName }}:{{ .Values.global.dockerTag }}
          ports:
            - name: Manager
              protocol: TCP
              containerPort: {{ .Values.manager.server.externalPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.manager.server.basePath }}/actuator/health/readiness
              port: {{ .Values.manager.server.externalPort }}
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.manager.server.basePath }}/actuator/health/liveness
              port: {{ .Values.manager.server.externalPort }}
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 10
          resources:
            {{- toYaml .Values.manager.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.global.mountPath.config }}
            - name: secret
              mountPath: {{ .Values.global.mountPath.secret }}
      volumes:
        - name: config
          configMap:
            name: {{ .Chart.Namespace }}-config
        - name: secret
          secret:
            secretName: {{ .Chart.Namespace }}-secret