apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "manager.selectorLabels" . | nindent 4 }}
  ports:
    - name: manager
      protocol: TCP
      port: {{ .Values.manager.server.externalPort }}
      targetPort: {{ .Values.manager.server.internalPort }}