apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: "{{ .Values.global.redis.password }}"