apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    {{- include "auth.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.global.db.url | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.global.db.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.db.password | b64enc }}

  SPRING_DATA_REDIS_HOST: {{ .Values.global.redis.host | b64enc }}
  SPRING_DATA_REDIS_PORT: {{ .Values.global.redis.port | b64enc }}
  SPRING_DATA_REDIS_PASSWORD: {{ .Values.global.redis.password | b64enc }}

  JWT_TOKEN_ACCESS_SECRET: {{ .Values.global.jwt.access.secret | b64enc }}
  JWT_TOKEN_ACCESS_EXPIRATION: {{ .Values.global.jwt.access.expiration | b64enc }}
  JWT_TOKEN_ACCESS_COOKIE_NAME: {{ .Values.global.jwt.access.cookieName | b64enc }}

  JWT_TOKEN_REFRESH_SECRET: {{ .Values.global.jwt.refresh.secret | b64enc }}
  JWT_TOKEN_REFRESH_EXPIRATION: {{ .Values.global.jwt.refresh.expiration | b64enc }}
  JWT_TOKEN_REFRESH_COOKIE_NAME: {{ .Values.global.jwt.refresh.cookieName | b64enc }}
