apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  labels:
    {{ include  }}
data:
  spring.datasource.url: {{ .Values.auth.db.url | b64enc }}
  spring.datasource.password: {{ .Values.global.db.password | b64enc }}
  spring.datasource.username: {{ .Values.global.db.username | b64enc }}

  spring.data.redis.host: {{ .Values.global.redis.host | b64enc }}
  spring.data.redis.port: {{ .Values.global.redis.port | b64enc }}
  spring.data.redis.password: {{ .Values.global.redis.password | b64enc }}

  jwt.token.access.secret: {{ .Values.global.jwt.access.secret | b64enc }}
  jwt.token.access.expiration: {{ .Values.global.jwt.access.expiration | b64enc }}
  jwt.token.access.cookie-name: {{ .Values.global.jwt.access.cookieName | b64enc }}
  jwt.token.refresh.secret: {{ .Values.global.jwt.refresh.secret | b64enc }}
  jwt.token.refresh.expiration: {{ .Values.global.jwt.refresh.expiration | b64enc }}
  jwt.token.refresh.cookie-name: {{ .Values.global.jwt.refresh.cookieName | b64enc }}
