auth:
  whitelist: /signup, /login, /refresh, /logout, /captcha/validate
  allowed-origins: https://coding-contest.k-lab.su, http://coding-contest.k-lab.su, https://192.168.0.38:30443, http://192.168.0.38:30443
