spring:
  application:
    name: Manager
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
auth:
  whitelist: /groups, /swagger-ui.html, /v3/api-docs/**, /swagger-ui/**, /actuator, /actuator/**
  allowed-origins: http://localhost:5173
server:
  servlet:
    context-path: /api/v1/
kafka:
  topic:
    submission: submissionTopic
logging:
  level:
    root: info