spring:
  application:
    name: Manager
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db-changelog-master.xml
  kafka:
    producer:
      client-id: ${spring.application.name}
      enable-idempotence: true
      acks: all
      linger-ms: 100
      retry-backoff-ms: 1000
      delivery-timeout-ms: 30000
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

auth:
  whitelist: /groups, /swagger-ui.html, /v3/api-docs/**, /swagger-ui/**, /actuator, /actuator/**
  allowed-origins: http://localhost:5173

kafka:
  topics:
    submission:
      name: submissionTopic
      replication-factor: 1
      partitions: 4

housekeeping:
  solution-keep-days: 180

server:
  servlet:
    context-path: /api/v1/

logging:
  level:
    root: info