manager:
  replicas: 1
  dockerImageName: coding-contest-system-manager
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      memory: 2Gi

  kafka:
    linger: "100"
    retryBackoff: "1000"
    deliveryTimeout: "30000"

  housekeeping:
    solutionKeepDays: "180"

  profiles: prod

  server:
    basePath: /api/v1
    internalPort: 8080
    externalPort: 8080

  whitelist: "/groups, /swagger-ui.html, /v3/api-docs/**, /swagger-ui/**, /actuator, /actuator/**"
  allowedOrigins: "http://localhost:5173, https://coding-contest.k-lab.su, http://coding-contest.k-lab.su, https://192.168.0.38:30443, http://192.168.0.38:30443"

  logLevel:
    root: INFO
    manager: INFO
