apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "compiler.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.compiler.profiles | quote | default "prod" }}

  SERVER_SERVLET_CONTEXT_PATH: {{ .Values.compiler.server.basePath | quote }}
  SERVER_PORT: {{ .Values.compiler.server.internalPort | quote }}

  KAFKA_TOPICS_SUBMISSION_NAME: {{ .Values.global.kafka.topics.submission.name | quote }}
  KAFKA_TOPICS_SUBMISSION_REPLICATION_FACTOR: {{ .Values.global.kafka.topics.submission.replicationFactor | quote }}
  KAFKA_TOPICS_SUBMISSION_PARTITIONS: {{ .Values.global.kafka.topics.submission.partitions | quote }}

  COMPILER_TIMEOUT_SECONDS: {{ .Values.compiler.timeoutSeconds | quote }}
  COMPILER_MAX_OUTPUT_BYTES: {{ .Values.compiler.maxOutputBytes | quote }}
  COMPILER_WORKDIR: {{ .Values.compiler.workdir | quote }}

  LOGGING_LEVEL_ROOT: {{ .Values.compiler.logLevel.root | quote | default "INFO" }}
  LOGGING_LEVEL_COM_SHIMADY_CONTEST_COMPILER: {{ .Values.compiler.logLevel.compiler | quote | default "INFO" }}
