apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    {{- include "compiler.labels" . | nindent 4 }}
stringData:
  SPRING_DATASOURCE_URL: {{ .Values.global.db.url }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.db.password }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.global.db.username }}

  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.servers }}
