name: Publish Manager Image
on:
  workflow_run:
    workflows:
      - Test Manager
    types:
      - completed
    branches:
      - main
jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build Manager service
        run: ./gradlew manager:bootJar --no-daemon

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: ./manager
          file: ./manager/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/coding-contest-manager:latest